### ISSUE TITLE
How to Use 'oblakstudio/redisinsight:latest' in Docker Compose

### ISSUE THREAD

**Issue by k8s-learner** [oblakstudio/redisinsight#13]
Issue Description:
I am currently using a Docker Compose file to access AWS Elasticache, and I would like to migrate to RedisInsight version 2.X using the 'oblakstudio/redisinsight:latest' Docker image. However, I am encountering issues with this setup. I am seeking assistance on how to properly configure a Docker Compose file for 'oblakstudio/redisinsight:latest' or any documentation that can guide me through the process.

Docker Compose File (existing setup):

```
version: "3.7"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redisinsight
    ports:
      - "8080:80"
    environment:
      - FORWARD_HOST=redisinsight
      - FORWARD_PORT=8001
      - BASIC_USERNAME=app
      - BASIC_PASSWORD=dddX3ddPil84J
    networks:
      - mynetwork

  redisinsight:
    image: redislabs/redisinsight:latest
    expose:
      - "8001"
    ports:
      - "8001:8001"
    environment:
      - RITRUSTEDORIGINS=http://localhost:8001 # Trust the proxy origin
      - RIPROXYENABLE=t
      - RILOGLEVEL=DEBUG
    volumes:
      - redisinsight:/db
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  redisinsight:
```
  
  
  I would like to transition to using the 'oblakstudio/redisinsight:latest' Docker image to take advantage of RedisInsight version 2.X. If anyone has experience with this image or can provide guidance on how to configure a Docker Compose file for it, I would greatly appreciate it. Additionally, if there are any specific configurations or environment variables required to make this work, please share those details as well.

Thank you for your assistance!
