### ISSUE TITLE
Enhance Docker Image Security for Kubernetes Deployment

### ISSUE THREAD

**Issue by germanattanasio** [oblakstudio/redisinsight#2]
When deploying this Docker image in a Kubernetes cluster, I've had to disable key security features, namely running as a non-root user and disallowing privilege escalation. To improve security posture, I propose these enhancements:

1. Modify the Dockerfile to create a non-root user that has read/write access to the working directory.
2. Remove the necessity for privilege escalation, aligning the image with Kubernetes' best practices.

I often use the following `securityContext` in my Kubernetes deployments or StatefulSets:

```yml
    securityContext:
      runAsUser: 1001
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
```

Implementing these changes will make it easier for users to adhere to security best practices without requiring manual adjustments.
