### ISSUE TITLE
[Question] Path where the Redis database information shown on the screen is saved

### ISSUE THREAD

**Issue by sdYoo** [oblakstudio/redisinsight#8]
Hello,

When the container is lowered or raised, the stored database information is initialized.
Where is the database information stored?

**Comment by sdYoo** [comment]
This is when restarting the container after stopping.

**Comment by micgruber** [comment]
I would be also interested because I want to use the image in kuberntes and want to save the settings if a container gets restarted. With the old image you can mount a volume to /db and all information will be stored:

`---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redisinsight-pv-claim
  namespace: redis
  labels:
    app: redisinsight
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight
  namespace: redis
  labels:
    app: redisinsight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisinsight
  template:
    metadata:
      labels:
        app: redisinsight
    spec:
      containers:
        - name:  redisinsight
          image: registry.dmz.liebherr.com/dockerhub_pullthrough/oblakstudio/redisinsight:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: db
              mountPath: /db
          ports:
            - containerPort: 5000
              protocol: TCP
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: redisinsight-pv-claim
---`

**Comment by seebeen** [comment]
Hello.

I'll fix this in the next release.

**Comment by micgruber** [comment]
In the meanwhile I was able to find a temporär fix. You can create a config map containing the backup:

`kubectl create configmap flame --from-file=pipeline/k8s/common/dashboard/data/db.sqlite -n namespace`

and the use a init container to initialize the volume with the backup:

```yaml
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: flame
spec:
  selector:
    matchLabels:
      app: flame
  template:
    metadata:
      labels:
        app: flame
    spec:
      serviceAccountName: flame
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: prepare
          image: busybox
          command: [ "ash","-c" ]
          args: [ "cp /tmp/backup/db.sqlite /app/data/db.sqlite" ]
          volumeMounts:
            - name: data
              mountPath: /app/data
            - name: backup
              mountPath: /tmp/backup
      containers:
        - name: flame
          image: shokohsc/flame
          ports:
            - name: http
              containerPort: 5005
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          emptyDir: {}
        - name: backup
          configMap:
            name: flame
            items:
              - key: db.sqlite
                path: db.sqlite
```

You can copy the backup before from the running container with kubectl cp:

`kubectl cp namespace/flame-ff4cc8cf-6gwq2:/app/data ./data`
